version: 2

defaults: &defaults
  docker:
    - image: cimg/python:3.11.1
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      pip install --user tox
      

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project/diabetes-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox
  publish_docker_image_to_aws:
    <<: *defaults
    working_directory: ~/project/
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publishing docker image to aws ECR
          command: |
            pip install awscli
            eval $(aws ecr get-login --no-include-email --region ap-southeast-2)
            make build-ml-api-aws tag-ml-api push-ml-api-aws
            aws ecs update-service --cluster ml-api-cluster --service custom-service --task-definition  first-run-task-definition --force-new-deployment


tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 2
  test_and_push_api:
    jobs:
      - test_app
      - publish_docker_image_to_aws:
          requires:
            - test_app
          filters:
            branches:
              only:
                - main
